### ISSUE TITLE
Error Using friendsIds() 

### ISSUE THREAD

**Issue by atktgs** [istrategylabs/node-twitter#34]
I tried to use the function friendsIds() but end up seeing following problem, switch the function name to statusesHomeTimeline() and everything works fine, any idea?

~/D/nodejs_test> node node_twitter_test.js 

~Desktop/nodejs_test/node_twitter_test.js:10
twitterRestClient.friendsIds( {}, function(error, result) {
                  ^
TypeError: Object [object Object] has no method 'friendsIds'
    at Object.<anonymous> (/Users/yitao.wang/Desktop/nodejs_test/node_twitter_test.js:10:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

**Comment by joesolly** [comment]
are you using the right version of code?

**Comment by atktgs** [comment]
@joesolly , problem located. I use the "npm install node-twitter" and the library don't have the friendsIds() function.
